# 系统管理項目配置文件

AdminDictURL = "/camel/rest/admin/dicts"
AdminDictsTypesListURL = "/camel/rest/admin/dicts/types/list"

usersURL = "/camel/rest/users"
dutyURL = "/camel/rest/dutys"
orgURL = "/camel/rest/orgs"
appsURL = "/camel/rest/system/applications"
workgroupURL = "/camel/rest/workgroups"
dataauthURL = "/camel/rest/dataauths"
addusersURL = "/camel/rest//dataauths/[id]/users"
userBtnPermissionPrefix = "admin:permissionModule:userMenu:"
workGroupBtnPermissionPrefix = "admin:permissionModule:workGroupMenu:"
dataAuthBtnPermissionPrefix = "admin:permissionModule:dataAuthMenu:"
AdminCacheKey = "ADMIN-DICT-KEY"

[[DutyButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[DutyButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[DutyButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true

[[OrgToolbarList]]
  id = "view"
  title = "查看"
  icon = "icon-view"
  type = "success"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[OrgToolbarList]]
  id = "edit"
  title = "编辑"
  icon = "icon-edit"
  type = "info"
  isShow = true
  isPermission = true
[[OrgToolbarList]]
  id = "delete"
  title = "删除"
  icon = "icon-delete"
  type = "danger"
  isShow = true
  isPermission = true

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "addUser"
  title = "添加用户"
  isShow = true
  isPermission = true

[[WorkGroupComponent]]
 path = "admin/workgroup/workgroupView"
 name = "AdminWorkGroupView"
[[WorkGroupComponent]]
 path = "admin/workgroup/workgroupAdd"
 name = "AdminWorkGroupAdd"
[[WorkGroupComponent]]
 path = "admin/workgroup/workgroupSearch"
 name = "AdminWorkGroupSearch"

[[UserComponent]]
 path = "admin/user/userEdit"
 name = "AdminUserEdit"
[[UserComponent]]
 path = "admin/user/userAdd"
 name = "AdminUserAdd"
[[UserComponent]]
 path = "admin/user/userSearch"
 name = "AdminUserSearch"

[[DataAuthComponent]]
 path = "admin/dataauth/dataauthView"
 name = "AdminDataAuthView"
[[DataAuthComponent]]
 path = "admin/dataauth/dataauthAdd"
 name = "AdminDataAuthAdd"
[[DataAuthComponent]]
 path = "admin/dataauth/dataauthSearch"
 name = "AdminDataAuthSearch"
[[DataAuthComponent]]
 path = "admin/dataauth/dataauthAddUser"
 name = "AdminDataAuthAddUser"

 [[orgComponent]]
  path = "admin/duty/dutyView"
  name = "AdminDutyView"
 [[DutyComponent]]
  path = "admin/duty/dutyAdd"
  name = "AdminDutyAdd"
 [[DutyComponent]]
  path = "admin/duty/dutySearch"
  name = "AdminDutySearch"


 [[OrgComponent]]
  path = "admin/org/orgView"
  name = "AdminOrgView"
 [[OrgComponent]]
  path = "admin/org/orgEdit"
  name = "AdminOrgEdit"
 [[OrgComponent]]
  path = "admin/org/orgAdd"
  name = "AdminOrgAdd"
 [[OrgComponent]]
  path = "admin/org/orgSearch"
  name = "AdminOrgSearch"
